WINDOW_SIZE = 4096
EPOCH = 20 # test with 50 for transformer based models
PATIENCE = 5
BATCH_SIZE = 8
LEARNING_RATE = 0.0001
NUM_PROC_WORKERS_DATA = 12
RANDOM_SEED = 42

def get_dict():
    return {
        "WINDOW_SIZE": WINDOW_SIZE,
        "TRAINING_STEP": TRAINING_STEP,
        "TESTING_STEP": TESTING_STEP,
        "RANDOM_SEED": RANDOM_SEED,
        "EPOCH": EPOCH,
        "PATIENCE": PATIENCE,
        "BATCH_SIZE": BATCH_SIZE,
        "LEARNING_RATE": LEARNING_RATE,
        "NUM_PROC_WORKERS": NUM_PROC_WORKERS_DATA
    }
