#WINDOW_SIZE = 8192
#TRAINING_STEP = 4096
WINDOW_SIZE = 12288
TRAINING_STEP = WINDOW_SIZE // 2

#TESTING_STEP = 8192
TESTING_STEP = WINDOW_SIZE

RANDOM_SEED = 42

EPOCH = 20 # test with 50 for transformer based models
PATIENCE = 5
BATCH_SIZE = 8
LEARNING_RATE = 0.0001
                

NUM_PROC_WORKERS_DATA = 12

def get_dict():
    return {
        "WINDOW_SIZE": WINDOW_SIZE,
        "TRAINING_STEP": TRAINING_STEP,
        "TESTING_STEP": TESTING_STEP,
        "RANDOM_SEED": RANDOM_SEED,
        "EPOCH": EPOCH,
        "PATIENCE": PATIENCE,
        "BATCH_SIZE": BATCH_SIZE,
        "LEARNING_RATE": LEARNING_RATE,
        "NUM_PROC_WORKERS": NUM_PROC_WORKERS_DATA
    }